module.exports = {
  products: [
      {
          _id: '1',
          name: 'iPhone 11 64 Gb - Preto',
          category: 'Smartphone',
          image: '/images/product-1.jpg',
          price: 4.500,
          brand: 'Apple',
          rating: 4.5,
          numReviews: 654,
          countInStock: 4,
      },
      {
          _id: '2',
          name: 'Moto E7',
          category: 'Smartphone',
          image: '/images/product-2.jpg',
          price: 640,
          brand: 'Motorola',
          rating: 4,
          numReviews: 345,
          countInStock: 5,
      },
      {
          _id: '3',
          name: 'Galaxy A02s',
          category: 'Smartphone',
          image: '/images/product-3.jpg',
          price: 969,
          brand: 'Samsung',
          rating: 4,
          numReviews: 546,
          countInStock: 7,
      },
      {
          _id: '4',
          name: 'Redmi',
          category: 'Smartphone',
          image: '/images/product-4.jpg',
          price: 1.029,
          brand: 'Xiaomi',
          rating: 3.5, 
          numReviews: 847,
          countInStock: 10,
      },
      {
          _id: '5',
          name: 'Asus Zenfone 3 Max',
          category: 'Smartphone',
          image: '/images/product-5.jpg',
          price: 999,
          brand: 'Zenfone',
          rating: 4,
          numReviews: 456,
          countInStock: 17,
      },
      {
          _id: '6',
          name: 'LG K62+',
          category: 'Smartphone',
          image: '/images/product-6.jpg',
          price: 1.149,
          brand: 'LG',
          rating: 4,
          numReviews: 422,
          countInStock: 3,
      },
      {
          _id: '7',
          name: 'Moto E7 Power',
          category: 'Smartphone',
          image: '/images/product-7.jpg',
          price: 711,
          brand: 'Motorola',
          rating: 3,
          numReviews: 10,
          countInStock: 5,
      },
      {
          _id: '8',
          name: 'Galaxy S20 Fe',
          category: 'Smartphone',
          image: '/images/product-8.jpg',
          price: 2.349,
          brand: 'Samsung',
          rating: 4.5,
          numReviews: 450,
          countInStock: 12,
      },
  ],
};